; ==========================================
; PHP設定ファイル
; ==========================================
;
; PHP設定を変更したい場合に記載する
;
; 例)
; - アップロード容量
; - メモリ上限
; - 実行時間
; - タイムゾーン
; - エラーログ設定
;
; 使用する場合は
; docker-compose.yml または Dockerfile で読み込む
; 例) Dockerfile で使用する場合
; COPY ./docker/php/php.ini /usr/local/etc/php/php.ini