; ==========================================
; Xdebug設定
; ==========================================

; デバッグ機能を有効化
xdebug.mode=debug

; yes
; リクエスト開始時に自動でデバッグ接続を開始
;
; trigger
; Xdebug Helper拡張をいれて必要な時にONにする設定
xdebug.start_with_request=yes

; Xdebugの接続先
;
; ホスト側のVS CodeでPHP Debug拡張が9003を待ち受ける構成なら、Dockerコンテナから見たホストPCを指す host.docker.internal を使う。
; ※「実行中のコンテナにアタッチして作業」= コンテナ内の認識だが internal で Xdebug が動かなくなる時がある
;    その時は 127.0.0.1 に書き換えてみる。通常はこのままで動くので書き換え不要
; xdebug.client_host=host.docker.internal
;
; 変更後反映確認
; php -i | grep -E "xdebug.mode|xdebug.start_with_request|xdebug.client_host|xdebug.client_port"
; ※これでhostが変わってるか確認。変わってなければ再ビルドで再起動する docker compose up -d --build
xdebug.client_host=127.0.0.1

; Xdebug3の標準ポート
xdebug.client_port=9003