; ==========================================
; Xdebug設定
; ==========================================

; デバッグ機能を有効化
xdebug.mode=debug

; yes
; リクエスト開始時に自動でデバッグ接続を開始
;
; trigger
; Xdebug Helper拡張をいれて必要な時にONにする設定
xdebug.start_with_request=yes

; Dockerコンテナから見たホストPCのホスト名(internal)
xdebug.client_host=host.docker.internal

; Xdebug3の標準ポート
xdebug.client_port=9003