services:
  # ==========================================
  # PHP(Laravel)コンテナ
  # ==========================================
  app:

    # Dockerfileからイメージを作成する
    build:
      # Dockerが参照する起点フォルダ (docker-compose.yml がある場所)
      context: .
      dockerfile: docker/php/Dockerfile

    # コンテナ名
    container_name: laravel_app

    # コンテナ内の作業ディレクトリ
    working_dir: /var/www/src

    # PJ全体を /var/www に共有する
    #
    # 左側  = ローカルPC側
    # 右側  = Docker側
    #
    # . = Docker、Git、Laravel全部入ってるPJルート
    # src配下=Laravelソースコード 
    # PJフォルダ全体でDocker+LaravelをGit管理しているため、srcだけでなくPJフォルダ全体を共有する
    volumes:
      - .:/var/www

    # dbコンテナ起動後にapp起動
    depends_on:
      - db

  # ==========================================
  # Webサーバー(Nginx)
  # ==========================================
  nginx:

    # 公式Nginxイメージ(最新安定版(Stable))を利用
    image: nginx:1.30.2

    container_name: laravel_nginx

    # ポート公開
    #
    # localhost:8080
    # ↓
    # nginx:80
    #
    ports:
      - "8080:80"

    volumes:

      # Laravelソース共有
      # PJ全体を /var/www に共有する
      # appと同じ設定にする：public配下のファイルを探してappへ渡すため
      - .:/var/www

      # nginx設定読み込み
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - app

  # ==========================================
  # MySQL
  # ==========================================
  db:

    # 公式MySQLイメージ(最新8.4 LTS)を利用
    image: mysql:8.4.9

    container_name: laravel_mysql

    restart: always

    environment:

      # 作成するDB名
      MYSQL_DATABASE: laravel

      # 一般ユーザー
      MYSQL_USER: laravel

      # 一般ユーザーパスワード
      MYSQL_PASSWORD: password

      # rootパスワード
      MYSQL_ROOT_PASSWORD: root

    ports:

      # MySQLクライアント接続用
      #
      # DBeaver
      # TablePlus
      # MySQL Workbench
      #
      # ローカルで3306つかっていたので、PC側のポートを3307に変更
      # DBeaverで見るときは3307に接続する
      - "3307:3306"

    volumes:

      # DB永続化
      #
      # コンテナ削除しても
      # DBが消えない
      #
      - dbdata:/var/lib/mysql

# ==========================================
# 名前付きVolume
# ==========================================
#
# MySQLデータ保存領域
#
volumes:
  dbdata:
