server {

    # Webサーバー待受ポート
    # Webサーバーがクライアントからのリクエストを待ち受けるポート番号を指定する
    #
    # 以下は慣習でほぼ固定で使われるポート番号
    # 80 = HTTP
    # 443 = HTTPS
    listen 80;


    # デフォルトファイル（ファイル指定がない場合に表示されるファイル）
    index index.php index.html;

    # 画像ではみ出たのでとりあえず 指定なしデフォ → 10M に変更（Laravel側で2M程度に制限はしてる）
    client_max_body_size 10M;

    # ドキュメントルート
    # Laravel公開ディレクトリ
    #
    # localhost:8080でアクセスした場合に表示されるディレクトリ
    # /var/www/配下にはPJ全体（Docker,git,Laravel）が入ってるので、公開はLaravelの公開ディレクトリであるpublicにする
    # public/index.php
    #
    root /var/www/src/public;


    # =========================
    # URLアクセス
    # =========================
    location / {

        # Laravelルーティングへ渡す
        # 
        # Nginxの定番設定
        #
        # try_files = クライアントからのリクエストURLに対応するファイルが存在するか、左から順に確認する
        # $uri = クライアントからのリクエストURL(ファイルがあれば表示する)
        # $uri/ = クライアントからのリクエストURL (ディレクトリがあれば表示する)
        # /index.php  = ファイルもディレクトリも無かった場合、ルート(public/index.php)に処理を渡す
        # ?$query_string = GETパラメータをそのままLaravelへ渡す
        try_files $uri $uri/ /index.php?$query_string;

    }


    # =========================
    # PHP処理(FastCGIの設定)
    #
    # FastCGI：Webサーバ上で動くプログラム(PHP)を動きを速くしたりWebサーバの負荷を軽減することができる仕組み
    # =========================
    location ~ \.php$ {

        # PHPファイルへのアクセスはNginx自身では処理せず、PHP-FPMへ渡す(appコンテナの9000番ポート)
        # app = docker-compose.yml の appサービス名
        # 9000 = PHP-FPMが待ち受けているポート
        fastcgi_pass app:9000;

        # ディレクトリにアクセスされた時にデフォルトで使うPHPファイル
        fastcgi_index index.php;

        # PHP-FPMに「実行するPHPファイルのフルパス」をを伝えるためのパラメータ
        # fastcgi_param = FastCGI(PHP-FPM)へ設定値を渡す命令
        # SCRIPT_FILENAME = PHP-FPM側で決められているパラメータ名(実行するPHPファイルのフルパス)
        # $document_root = Nginxの root で指定した場所(/var/www/src/public)
        # $fastcgi_script_name = 実行対象のPHPファイル名
        #
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        # FastCGIでよく使う基本パラメータを読み込む
        #
        # 例:
        # REQUEST_METHOD
        # QUERY_STRING
        # CONTENT_TYPE
        # REQUEST_URI
        #
        # などをPHP-FPMへ渡す
        include fastcgi_params;
    }

}